sudo: false
language: c
dist: focal
compiler:
  - gcc
  - clang
script: s/travis-build
addons:
  apt:
    packages:
      - libbsd-dev
      - libdb-dev
      - libtolua-dev
      - libncurses5-dev
      - libsqlite3-dev
      - libexpat1-dev
      - libiniparser-dev
      - libcjson-dev
      - cppcheck
      - shellcheck
      - luarocks
os:
  - linux
