language: c
compiler:
  - gcc
  - clang
script: s/travis-build
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libtolua-dev liblua5.2-dev libncurses5-dev libsqlite3-dev libxml2-dev 
