sudo: false
language: c
compiler:
  - gcc
  - clang
script: s/travis-build
addons:
  apt:
    packages:
      - libtolua-dev
      - liblua5.2-dev
      - libncurses5-dev
      - libsqlite3-dev
      - libxml2-dev
os:
  - linux
  - osx
