# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: debian-buster

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Update APT
        run: sudo apt update
      - name: Install dependencies
        run: sudo apt install libexpat1-dev libtolua-dev libncurses5-dev libsqlite3-dev libiniparser-dev libcjson-dev libbsd-dev cppcheck shellcheck luarocks clang-tools iwyu
      - name: Run CTest
        uses: HorstBaerbel/action-ctest@1.1
        with:
          sourcedir: '.'
          builddir: build
          cmakeoptions: '--config Debug'
          ctestoptions: ''
  test:
    needs: build
    steps:
      - name: Tests
        working-directory: tests
        run: ../build/eressea/eressea -v1 ../scripts/run-tests.lua
        run: ../build/eressea/eressea -v1 ../scripts/run-tests-e2.lua
        run: ../build/eressea/eressea -v1 ../scripts/run-tests-e3.lua

